# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ObjectiveC-Lib/Specs.git'

platform :ios, '10.0'
inhibit_all_warnings!

target 'HJTraceLoggerDemo' do
  pod 'HJTraceLogger', :path => '../'
#  pod 'HJTraceLogger'
  pod 'SVProgressHUD'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end
